apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crd }}
spec:
  group: {{ .Values.group }}
  names:
    kind: {{ .Values.kind }}
    listKind: {{ .Values.kind }}List
    plural: {{ .Values.resource }}
    singular: {{ .Values.name }}
  scope: Cluster
  versions:
    - name: {{ .Values.version }}
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                managementState:
                  type: string
                  enum: [Managed, Removed]
                  default: Removed
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status, lastTransitionTime]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      severity:
                        type: string
                      observedGeneration:
                        type: integer
                        format: int64
                      lastTransitionTime:
                        type: string
                        format: date-time
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                releases:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: [name]
                  items:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      repoUrl:
                        type: string
          x-kubernetes-validations:
            - message: {{ printf "%s must be named cluster" .Values.kind | quote }}
              rule: self.metadata.name == 'cluster'
