apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    opendatahub.io/managed: "false"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-kserve
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-kserve
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames: ["kserves.kserve.example.odh.io"]
    verbs: ["get"]
  - apiGroups: ["kserve.example.odh.io"]
    resources: ["kserves"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kserve.example.odh.io"]
    resources: ["kserves/status"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-kserve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-kserve
subjects:
  - kind: ServiceAccount
    name: example-kserve
    namespace: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-kserve
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.config.replicas | default 1 }}
  selector:
    matchLabels:
      app: example-kserve
  template:
    metadata:
      labels:
        app: example-kserve
    spec:
      serviceAccountName: example-kserve
      containers:
        - name: controller
          image: {{ .Values.image | quote }}
          imagePullPolicy: Always
          command: ["/manager"]
          args: ["run", "module", "kserve"]
          env:
            - name: PLATFORM_MODULES_DIR
              value: /config/modules
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
