apiVersion: v2
name: aigateway-controller
version: 0.1.0
description: Installs the example AI Gateway CRD and module controller.
dependencies:
  - name: module
    version: 0.1.0
    condition: module.enabled
  - name: projections
    version: 0.1.0
    condition: projections.enabled
