//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmComponent) DeepCopyInto(out *HelmComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmComponent.
func (in *HelmComponent) DeepCopy() *HelmComponent {
	if in == nil {
		return nil
	}
	out := new(HelmComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmComponentList) DeepCopyInto(out *HelmComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmComponentList.
func (in *HelmComponentList) DeepCopy() *HelmComponentList {
	if in == nil {
		return nil
	}
	out := new(HelmComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmComponentSpec) DeepCopyInto(out *HelmComponentSpec) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmComponentSpec.
func (in *HelmComponentSpec) DeepCopy() *HelmComponentSpec {
	if in == nil {
		return nil
	}
	out := new(HelmComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmComponentStatus) DeepCopyInto(out *HelmComponentStatus) {
	*out = *in
	in.ReleaseStatus.DeepCopyInto(&out.ReleaseStatus)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmComponentStatus.
func (in *HelmComponentStatus) DeepCopy() *HelmComponentStatus {
	if in == nil {
		return nil
	}
	out := new(HelmComponentStatus)
	in.DeepCopyInto(out)
	return out
}
